version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}-{{ checksum "buildSrc/src/main/kotlin/Dependencies.kt" }}
      - run:
          name: Accept Android licenses
          command: sdkmanager --licenses
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}-{{ checksum "buildSrc/src/main/kotlin/Dependencies.kt" }}
      - run:
          name: Run Build
          command: ./gradlew :app:assembleDebug
      - run:
          name: Run Unit Tests
          command: ./gradlew :app:testDebugUnitTest
      - store_artifacts:
          path: app/build/outputs/apk
          destination: build/outputs/apk
      - store_test_results:
          path: app/build/test-results
